filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/spring/geo/*.log
#    - /var/log/analytics/*.log

# filebeat.modules:
# - module: nginx
#   access:
#     var.paths: ["/var/log/nginx/access.log"]
#   error:
#     var.paths: ["/var/log/nginx/error.log"]

output.logstash:
  enabled: true
  hosts: ["logstash:5035"]

# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]
#   username: "elastic"
#   password: "some_password"

#setup.kibana:
#  host: "http://kibana:5601"
#  username: "elastic"
#  password: "some_password"
